# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: Mine
    filters: is:open author:@me repo:dlvhdr/gh-dash updated:>={{ nowModify "-3w" }} sort:updated-desc
    layout:
      author:
        hidden: true
      repoName:
        hidden: true
  - title: Review
    filters: repo:dlvhdr/gh-dash -author:@me is:open updated:>={{ nowModify "-2.5w" }}
    layout:
      repoName:
        hidden: true
  - title: All
    filters: repo:dlvhdr/gh-dash
issuesSections:
  - title: Open
    filters: repo:dlvhdr/gh-dash is:open sort:reactions
  - title: Bugs
    filters: repo:dlvhdr/gh-dash is:open sort:reactions label:bug
  - title: Features
    filters: repo:dlvhdr/gh-dash is:open sort:reactions label:feat
  - title: High
    filters: repo:dlvhdr/gh-dash is:open sort:reactions label:high-pri
  - title: Mid
    filters: repo:dlvhdr/gh-dash is:open sort:reactions label:mid-pri
  - title: Low
    filters: repo:dlvhdr/gh-dash is:open sort:reactions label:mid-pri
  - title: Unlabeled
    filters: repo:dlvhdr/gh-dash is:open sort:reactions -label:bug -label:feat
  - title: All
    filters: repo:dlvhdr/gh-dash sort:reactions

defaults:
  view: prs
  refetchIntervalMinutes: 5
  layout:
    prs:
      repoName:
        hidden: true
      base:
        hidden: true

  preview:
    open: true
    width: 84
  prsLimit: 20
  issuesLimit: 20
