project_name: gh-prs

release:
  prerelease: auto
  draft: true
  name_template: "gh-prs v{{ .Version }}"

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/gh-prs
      main: ./

    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64]

    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]

archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_v{{ .Version }}_{{ .Arch }}"

    wrap_in_directory: true
    replacements:
      darwin: macos
    format: zip

  - id: windows
    builds: [windows]
    <<: *archive_defaults
    wrap_in_directory: false
    format: zip

nfpms:
  - license: ISC
    maintainer: Dolev Hadar
    homepage: https://github.com/dlvhdr/gh-prs
    bindir: /usr
    file_name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Arch }}"
    dependencies:
      - gh
    description: gh cli extension to display a dashboard of PRs - configurable with a beautiful UI.
    formats:
      - deb
      - rpm
