#!/bin/bash

set -e

# TODO: Read repos and sections from config file
# TODO: Get it in JSON format so I can style it any way I want
# gh pr list --json "title,mergeable,author,url,additions,headRefName,headRepository,isDraft,number,reviewDecision,state,statusCheckRollup,updatedAt" --author @me | jq | less -r
# status | title | repo | headRefName | pr # | ci | meargable | changes | author | updated | url

repos=("wix-private/wix-code-code-editor") #, "wix-incubator/corvid-types", "wix-private/wix-code-devex")
fields="title,mergeable,author,url,additions,headRefName,headRepository,isDraft,number,reviewDecision,state,statusCheckRollup,updatedAt" 
title_max_len=35

printf "\n"
figlet -f digital "My Pull Requests"
pr_lines=""
for repo in "${repos[@]}"
	 do
		  while read pr_response; do
				pr_title=`echo $pr_response | jq -r '.title' | cut -c -${title_max_len}`
				pr_review_decision=`echo $pr_response |
						jq -r 'if .reviewDecision == ""
						 then "WAITING_FOR_REVIEW"
						 else .reviewDecision
						 end'`
				# pr_line=`printf "%s **| %s\n" "${pr_review_decision}" "${pr_title}"`
				pr_line=`echo "${pr_review_decision} **| ${pr_title}\n"`
				# echo $pr_line
				pr_lines="${pr_lines}${pr_line}"
				# echo "$pr_review_decision |  $pr_title" | column -s "| " -t
				#  echo $pr_response |
				# 		jq -cr '
				# 			 [
				# 					.headRepository.name,
				# 					.author.login,
				# 					.updatedAt
				# 			 ]' |
				# 		sed 's/^\[//g' | sed 's/\]$//g' |
				# 		column -s "," -t
			done < <(gh pr --repo $repo list --author @me --json $fields | jq -c '.[]')
   # for pr in "${repo_prs[@]}"
   # do
   #    printf "$pr\n"
   # done
	 echo $pr_lines | sed 's/\\n/\n/g' | column -s "**" -t
done

printf "\n"
figlet -f digital "Review Requested"
for i in "${arr[@]}"
do
   gh pr --repo $i list --assignee @me
done

