# https://taskfile.dev

version: "3"
silent: true

tasks:
  default:
    desc: Run
    cmds:
      - go run . {{.CLI_ARGS}}
    interactive: true

  build:
    desc: Build
    cmds:
      - go build .

  uninstall:
    desc: Uninstall from the gh extensions
    cmd: |
      if gh ext list | grep --quiet 'gh dash'; then echo "🕐 Uninstalling..."; gh ext remove dash; fi
      exit 0

  install:
    desc: Install the local app as a gh extension
    cmds:
      - task: build
      - task: uninstall
      - echo "🕐 Installing local build..." && gh ext install .
      - gh dash --version

  install:prod:
    desc: Install the latest available version as a gh extension
    cmds:
      - task: uninstall
      - echo "🕐 Installing latest version..." && gh ext install dlvhdr/gh-dash
      - gh dash --version

  debug:
    desc: Run in debug mode. Run `task logs` to watch the logs.
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - DEBUG=true go run . --debug {{.CLI_ARGS}}
    interactive: true

  debug:warn:
    desc: Run in debug mode, only log warning. Run `task logs` to watch the logs.
    cmds:
      - printf "~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n~\n―――――――――――――――――――――――――――――――――――――――――――――――\n" > ./debug.log
      - LOG_LEVEL=warn DEBUG=true go run . --debug {{.CLI_ARGS}}
    interactive: true

  dlv:
    desc: Debug with dlv
    cmds:
      - dlv debug --headless --api-version=2 --listen=127.0.0.1:43000 .

  logs:
    desc: Tail the debug logs
    cmds:
      - rm -f ./debug.log
      - touch ./debug.log
      - tail -f ./debug.log
    interactive: true

  lint:
    desc: Run base linters
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m
    env:
      GOEXPERIMENT: null

  lint:fix:
    desc: Run base linters and fix issues
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix
    env:
      GOEXPERIMENT: null

  test:one:
    desc: Run a test
    cmds:
      - gotip

  test:rerun:
    cmds:
      - gotip --rerun
    desc: Rerun the last test

  test:
    desc: Run tests
    cmds:
      - prism test {{.CLI_ARGS}} ./...

  fmt:
    desc: Run gofumpt
    cmds:
      - gofumpt -w $(git ls-files '*.go')

  check-nerd-font:
    desc: Find broken nerdfont characters
    cmds:
      - nerdfix check $(fd --extension go)

  fix-nerd-font:
    desc: Fix broken nerdfont icons
    cmds:
      - nerdfix fix --format=json $(fd --extension go)

  docs-prepare:
    cmds:
      - cd docs && pnpm i

  docs:
    cmds:
      - cd docs && pnpm dev {{.CLI_ARGS}}
    desc: Start docs server

  docs-build:
    desc: Run docs production build
    cmds:
      - task: docs-prepare
      - cd docs && pnpm build

  docs-preview:
    desc: Preview docs production build
    cmds:
      - task: docs-build
      - cd docs && pnpm preview

  docs-sponsors:
    desc: Update OpenCollective and GitHub sponsors list
    cmds:
      - which sponsors || go install github.com/goreleaser/sponsors@main
      - sponsors generate --config gh://dlvhdr/sponsors/sponsors.yml sponsors.json
      - sponsors apply sponsors.json gh://dlvhdr/sponsors/readme.tpl.md ./README.md
    sources:
      - ./README.md
      - ./.github/sponsors/sponsors.json
      - ./.github/sponsors/sponsors.yml
    generates:
      - ./README.md
      - ./.github/sponsors/sponsors.json
