name: build

on:
  pull_request:
    paths-ignore:
      - "docs/**"

permissions:
  contents: read

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: Download Go modules
        run: go mod download
      - name: Build
        run: go build ./...
